process_names:
  - name: "payload"
    cmdline:
      - "/lib/irobot_benchmark/irobot_benchmark"
  - name: "datamgmt"
    cmdline:
      - "/lib/datamgmt/datamgmt"
  - name: "continuous"
    cmdline:
      - "/lib/tracer/continuous"
  - name: "structural"
    cmdline:
      - "/lib/tracer/structural"
  - name: "FDL"
    cmdline:
      - "STREAM-FDL/build/main"