services:
  stream:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/ubuntu/stream:cached
    ports:
      - "9256:9256"
    tty: true
    working_dir: /home/ubuntu/stream
    # command: sleep infinity
    depends_on:
      - neo4j
      - influxdb

  neo4j:
    image: neo4j:5.26.1
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/123456789
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: KARTOFF8xE
      DOCKER_INFLUXDB_INIT_PASSWORD: 123456789
      DOCKER_INFLUXDB_INIT_ORG: TUBAF
      DOCKER_INFLUXDB_INIT_BUCKET: STREAM
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: WVvSEEbHPqeMFpcgWqThaEcU6u6SWJ-L26ct4oRuEJmKdMOk-ZG8XlKA5xcitJXENa2r2YNLNwxjE6-KKkx8xw==

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always
    depends_on:
      - influxdb
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
      - ./configs/grafana/provisionings:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-storage: